before:
  hooks:
    - go mod tidy
builds:
  - id: ctrld-darwin
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/ctrld
    hooks:
      post: gon gon.hcl
archives:
  - strip_parent_binary_folder: true
    wrap_in_directory: true
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
